/* eslint-disable @typescript-eslint/naming-convention */

export default {
    "BlankMap": "Map",
    "OceanMap": "Map",
    "EmptyMap": "Map",
    "SM_Cone": "StaticMesh",
    "SM_Cube": "StaticMesh",
    "SM_Cylinder": "StaticMesh",
    "SM_Plane": "StaticMesh",
    "SM_Sphere": "StaticMesh",
    "SM_Capsule": "StaticMesh",
    "SM_Pipe": "StaticMesh",
    "SM_QuadPyramid": "StaticMesh",
    "SM_Torus": "StaticMesh",
    "SM_TriPyramid": "StaticMesh",
    "SM_Tube": "StaticMesh",
    "SM_Wedge_A": "StaticMesh",
    "SM_Wedge_B": "StaticMesh",
    "SM_Ball_VR": "StaticMesh",
    "SM_Cube_VR_01": "StaticMesh",
    "SM_Cube_VR_02": "StaticMesh",
    "SM_Cube_VR_03": "StaticMesh",
    "SM_Pyramid_VR": "StaticMesh",
    "M_Default_Masked_Lit": "Materials",
    "M_Default_Masked_Unlit": "Materials",
    "M_Default_Translucent_Lit": "Materials",
    "M_Default_Translucent_Lit_Depth": "Materials",
    "M_Default_Translucent_Lit_Decal": "Materials",
    "M_Noise": "Materials",
    "M_Wireframe": "Materials",
    "P_Beam": "Particles",
    "P_Ribbon": "Particles",
    "P_DirectionalBurst": "Particles",
    "P_Fountain": "Particles",
    "P_HangingParticulates": "Particles",
    "P_OmnidirectionalBurst": "Particles"
};